server:
  port: 9001

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infra?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: localhost
    password: 123456


logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'