server:
  port: 9000
spring:
  application:
    name: infra-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由



management:
  endpoints:
    web:
      exposure:
        include: '*'
